# Generated by Django 4.2.16 on 2025-10-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitchain',
            name='sequencer_address',
            field=models.CharField(blank=True, help_text='The address of the L3 sequencer to monitor balance.', max_length=42),
        ),
    ]
