# Generated by Django 4.2.16 on 2025-10-30 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Monitor_app', '0002_orbitchain_sequencer_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orbitchain',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='latest_block_number',
            field=models.BigIntegerField(blank=True, help_text='The latest block number.', null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='rpc_chain_id',
            field=models.BigIntegerField(blank=True, help_text='The chain ID from the RPC.', null=True),
        ),
        migrations.AlterField(
            model_name='orbitchain',
            name='rpc_url',
            field=models.URLField(help_text='The RPC URL of the Orbit L3 chain.', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='orbitchain',
            unique_together={('user', 'rpc_url'), ('user', 'name')},
        ),
    ]
