# Generated by Django 4.2.16 on 2025-10-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor_app', '0003_alter_orbitchain_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbiItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('constant', models.BooleanField(null=True)),
                ('payable', models.BooleanField(null=True)),
                ('state_mutability', models.CharField(blank=True, max_length=50, null=True)),
                ('inputs', models.JSONField(default=list)),
                ('outputs', models.JSONField(default=list)),
                ('anonymous', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'ABI Item',
                'verbose_name_plural': 'ABI Items',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('bytecode', models.TextField(blank=True, null=True)),
                ('is_contract', models.BooleanField(default=True)),
                ('creator', models.CharField(blank=True, max_length=42, null=True)),
                ('creation_tx', models.CharField(blank=True, max_length=66, null=True, unique=True)),
                ('balance_eth', models.DecimalField(decimal_places=18, default=0.0, max_digits=30)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=0, max_digits=40, null=True)),
                ('decimals', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('block_number', models.BigIntegerField()),
                ('block_hash', models.CharField(max_length=66)),
                ('timestamp', models.DateTimeField()),
                ('nonce', models.IntegerField()),
                ('transaction_index', models.IntegerField()),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(blank=True, max_length=42, null=True)),
                ('value', models.DecimalField(decimal_places=0, max_digits=30)),
                ('gas', models.BigIntegerField()),
                ('gas_price', models.BigIntegerField()),
                ('gas_used', models.BigIntegerField()),
                ('cumulative_gas_used', models.BigIntegerField()),
                ('input_data', models.TextField()),
                ('method_id', models.CharField(blank=True, max_length=10, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_receipt_status', models.CharField(max_length=1)),
                ('is_error', models.BooleanField()),
                ('confirmations', models.BigIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Monitor_app.contract')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='notificationchannel',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='orbitchain',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orbitchain',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.DeleteModel(
            name='HealthMetric',
        ),
        migrations.DeleteModel(
            name='NotificationChannel',
        ),
        migrations.DeleteModel(
            name='OrbitChain',
        ),
        migrations.AddField(
            model_name='abiitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abi', to='Monitor_app.contract'),
        ),
    ]
